//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCBEntities : DbContext
    {
        public QLCBEntities()
            : base("name=QLCBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_CAPHAM> tb_CAPHAM { get; set; }
        public virtual DbSet<tb_CHUCDANH> tb_CHUCDANH { get; set; }
        public virtual DbSet<tb_CHUCVU> tb_CHUCVU { get; set; }
        public virtual DbSet<tb_DANTOC> tb_DANTOC { get; set; }
        public virtual DbSet<tb_DIEUCHUYEN> tb_DIEUCHUYEN { get; set; }
        public virtual DbSet<tb_DONVI> tb_DONVI { get; set; }
        public virtual DbSet<tb_KYLUAT> tb_KYLUAT { get; set; }
        public virtual DbSet<tb_KHENTHUONG> tb_KHENTHUONG { get; set; }
        public virtual DbSet<tb_LENHAM> tb_LENHAM { get; set; }
        public virtual DbSet<tb_TONGIAO> tb_TONGIAO { get; set; }
        public virtual DbSet<tb_THOIVIEC> tb_THOIVIEC { get; set; }
        public virtual DbSet<tb_TRINHDO> tb_TRINHDO { get; set; }
        public virtual DbSet<tb_CANBO> tb_CANBO { get; set; }
        public virtual DbSet<tb_BAOHIEM> tb_BAOHIEM { get; set; }
        public virtual DbSet<tb_TAIKHOAN> tb_TAIKHOAN { get; set; }
    }
}
