//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CAPHAM
    {
        public int MACH { get; set; }
        public string TENCAPHAM { get; set; }
        public Nullable<double> HESOLUONG { get; set; }
        public Nullable<int> NAMLEN { get; set; }
    }
}
