//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CANBO
    {
        public int MACB { get; set; }
        public string SOHIEU { get; set; }
        public string HOTEN { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public byte[] HINHANH { get; set; }
        public Nullable<int> MAPHONG { get; set; }
        public Nullable<int> MACV { get; set; }
        public Nullable<int> MATD { get; set; }
        public Nullable<int> MADT { get; set; }
        public Nullable<int> MABH { get; set; }
        public Nullable<int> MATG { get; set; }
        public Nullable<int> MACD { get; set; }
        public Nullable<int> MACH { get; set; }
        public Nullable<bool> DATHOIVIEC { get; set; }
    
        public virtual tb_CHUCDANH tb_CHUCDANH { get; set; }
        public virtual tb_CHUCVU tb_CHUCVU { get; set; }
        public virtual tb_DONVI tb_DONVI { get; set; }
        public virtual tb_TRINHDO tb_TRINHDO { get; set; }
    }
}
